stages:
  - build
  - test
  - deploy

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths:
    - build/

test_artifact:
  image: alpine
  stage: test
  script:
    - test -f build/index.html

unit_tests:
  image: node:22-alpine
  stage: test
  script:
    - npm ci
    - npm test
  artifacts:  #publish the junit report
    when: always #always publish the report (when it fail or when it pass)
    reports:
      junit: ./reports/junit.xml

netlify:
  image: node:22-alpine
  stage: deploy
  rules:
    - if : $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    #CI_COMMIT_REF_NAME: The branch or tag name for which project is built.
    #CI_DEFAULT_BRANCH: The name of the project’s default branch.
  variables:
    NETLIFY_SITE_ID: 'd31b585b-8d1d-4897-bf12-d1d9eeaa421f'
  script:
    - npm install -g netlify-cli
    - netlify --version
    - netlify status
    - echo "Depolying to project id $NETLIFY_SITE_ID"
    - netlify deploy --prod --dir=build --no-build
    - apk add curl # apk which stands for alpine package manager 
    # we use apk of the alpine linux distribution to install curl
    - curl 'https://tharushi-learn-gitlab.netlify.app' | grep 'GitLab'
    # curl use to check the website.
    # | (pipe chatacter) use to send the result of actually getting the contents of 
    # this website to the grep command, which has the ability of the searching the text