variables:
  VITE_APP_VERSION: $CI_COMMIT_SHORT_SHA

build_website:
  image: node:22-alpine
  stage: build
  script:
    - node --version
    - npm --version
    - npm ci
    - npm run build
  artifacts:
    paths: 
      - build/

ssh_deploy:
  stage: deploy
  image: alpine
  before_script:
    #check if port 22 is open on the server
    #- nc -zv 54.235.10.186 22
    - nc -zv $REMOTE_DEPLOY_HOST 22
    # change mode to grand read-only permission to owner
    # 400: read only permission
    - chmod 400 $SSH_PRIVATE_KEY
    - ls -l $SSH_PRIVATE_KEY 
    # Install openssh-client
    - apk add openssh-client
    #- ssh-agent # it is background process that manage SSH keys for authentication. we need thisSSH -Agent to add our key
    - eval $(ssh-agent) #To set these enviornments variables in curent shell sessions
    # Add the SSH key to the agent
    - ssh-add $SSH_PRIVATE_KEY
    # Create the SSH directory and assign the right permission
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Create the known_hosts file and assign the right permission
    - cp $SSH_KNOWN_HOSTS ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    # Open SSH connection + run the commands
    #  Old Code: - ssh -o StrictHostKeyChecking=no ec2-user@$REMOTE_DEPLOY_HOST # Should check to see if can establish an SSH connection to this remote server
    - ssh $REMOTE_DEPLOY_USER@$REMOTE_DEPLOY_HOST "whoami; touch /tmp/foo.txt; ls -l /tmp" # We can run multiple commands: whoami; touch /tmp/foo.txt; ls -l /tmp
    - scp build/* $REMOTE_DEPLOY_USER@$REMOTE_DEPLOY_HOST:user/share/nginx/html/ # Securely trasfer file (transfer all content of build directory. not build directory itself)